-- Flyway Migration V1 (H2): Initial schema for embedded desktop runtime
CREATE TABLE IF NOT EXISTS agent_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    raw_trace CLOB,
    compressed_summary CLOB,
    embedding BYTEA,
    relevance_score DOUBLE,
    trace_hash VARCHAR(64) UNIQUE,
    is_archived BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_agent_timestamp ON agent_memory(agent_name, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_agent_name ON agent_memory(agent_name);
CREATE INDEX IF NOT EXISTS idx_trace_hash ON agent_memory(trace_hash);

CREATE TABLE IF NOT EXISTS trace_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent VARCHAR(255) NOT NULL,
    input CLOB,
    output CLOB,
    tools_used CLOB,
    duration_ms INTEGER,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_compressed BOOLEAN DEFAULT FALSE,
    compressed_data BYTEA
);

CREATE INDEX IF NOT EXISTS idx_trace_agent ON trace_logs(agent);
CREATE INDEX IF NOT EXISTS idx_trace_timestamp ON trace_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_trace_agent_timestamp ON trace_logs(agent, timestamp DESC);

CREATE TABLE IF NOT EXISTS skills (
    name VARCHAR(255) PRIMARY KEY,
    version VARCHAR(50) NOT NULL,
    manifest_json CLOB NOT NULL,
    installed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_enabled BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS document_index (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path VARCHAR(1024) NOT NULL,
    chunk CLOB,
    embedding BYTEA,
    chunk_index INTEGER,
    full_text_search CLOB
);

CREATE INDEX IF NOT EXISTS idx_doc_path ON document_index(path);

CREATE TABLE IF NOT EXISTS trace_dedup (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_hash VARCHAR(64) UNIQUE NOT NULL,
    count INTEGER DEFAULT 1,
    last_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent_memory_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    raw_trace CLOB,
    compressed_summary CLOB,
    embedding BYTEA,
    archived_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_archive_agent_memory ON agent_memory_archive(agent_name);
CREATE INDEX IF NOT EXISTS idx_archive_memory_timestamp ON agent_memory_archive(archived_at DESC);

CREATE TABLE IF NOT EXISTS trace_logs_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent VARCHAR(255) NOT NULL,
    input CLOB,
    output CLOB,
    tools_used CLOB,
    duration_ms INTEGER,
    timestamp TIMESTAMP NOT NULL,
    archived_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_archive_agent ON trace_logs_archive(agent);
CREATE INDEX IF NOT EXISTS idx_archive_timestamp ON trace_logs_archive(archived_at DESC);

CREATE TABLE IF NOT EXISTS agent_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name VARCHAR(255) NOT NULL,
    session_id VARCHAR(64) UNIQUE NOT NULL,
    state_json CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_session_agent ON agent_sessions(agent_name);
CREATE INDEX IF NOT EXISTS idx_session_id ON agent_sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_session_active ON agent_sessions(is_active);

CREATE TABLE IF NOT EXISTS storage_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name VARCHAR(255) NOT NULL,
    metric_value DOUBLE,
    agent_name VARCHAR(255),
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_metrics_name ON storage_metrics(metric_name);
CREATE INDEX IF NOT EXISTS idx_metrics_agent ON storage_metrics(agent_name);
CREATE INDEX IF NOT EXISTS idx_metrics_timestamp ON storage_metrics(timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_memory_agent_archived ON agent_memory(agent_name, is_archived);
