CREATE TABLE IF NOT EXISTS generated_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id VARCHAR(255) NOT NULL UNIQUE,
    project_name VARCHAR(255) NOT NULL,
    project_type VARCHAR(100) NOT NULL,
    framework VARCHAR(100) NOT NULL,
    language VARCHAR(100) NOT NULL,
    description CLOB,
    file_count INTEGER NOT NULL DEFAULT 0,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    file_list CLOB,
    files_json CLOB
);

CREATE INDEX IF NOT EXISTS idx_project_id ON generated_projects(project_id);
CREATE INDEX IF NOT EXISTS idx_project_created ON generated_projects(created_at DESC);
