CREATE TABLE IF NOT EXISTS oauth_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connector_id VARCHAR(255),
  provider VARCHAR(255),
  access_token CLOB,
  refresh_token CLOB,
  expires_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
