CREATE TABLE IF NOT EXISTS pull_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(255) NOT NULL UNIQUE,
    model_name VARCHAR(255),
    status VARCHAR(100),
    message VARCHAR(1024),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pull_jobs_created_at ON pull_jobs(created_at);
