DROP TABLE IF EXISTS ingest_jobs;

CREATE TABLE IF NOT EXISTS ingest_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(255) NOT NULL UNIQUE,
    connector_type VARCHAR(100),
    status VARCHAR(50) NOT NULL DEFAULT 'queued',
    message VARCHAR(2048),
    items_processed INTEGER DEFAULT 0,
    items_failed INTEGER DEFAULT 0,
    bytes_ingested BIGINT DEFAULT 0,
    chunks_created INTEGER DEFAULT 0,
    source VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ingest_status ON ingest_jobs(status);
CREATE INDEX IF NOT EXISTS idx_ingest_connector_type ON ingest_jobs(connector_type);
CREATE INDEX IF NOT EXISTS idx_ingest_created_at ON ingest_jobs(created_at);
CREATE INDEX IF NOT EXISTS idx_ingest_job_id ON ingest_jobs(job_id);
CREATE INDEX IF NOT EXISTS idx_ingest_connector_status ON ingest_jobs(connector_type, status);
CREATE INDEX IF NOT EXISTS idx_ingest_created_status ON ingest_jobs(created_at DESC, status);
